// src/pages/BudgetPlan.tsx
import { useNavigate } from 'react-router-dom';
import { Card, Row, Col, Typography, Space } from 'antd';
import { TrendingUp, BarChart3, PiggyBank, ArrowRight } from 'lucide-react';

const { Title, Text } = Typography;

const budgetTypes = [
  {
    key: 'balance',
    title: '账户余额预测',
    description: '预测账户未来余额变化趋势',
    icon: <TrendingUp size={28} />,
    color: '#1677ff',
  },
  {
    key: 'trend',
    title: '收入支出趋势',
    description: '分析未来收支趋势和变化',
    icon: <BarChart3 size={28} />,
    color: '#52c41a',
  },
  {
    key: 'savings',
    title: '储蓄目标规划',
    description: '规划储蓄目标和实现进度',
    icon: <PiggyBank size={28} />,
    color: '#fa8c16',
  },
];

export const BudgetPlan = () => {
  const navigate = useNavigate();

  return (
    <div>
      <Title level={4} style={{ marginBottom: 16 }}>预算计划</Title>
      <Text type="secondary" style={{ display: 'block', marginBottom: 32, fontSize: 16 }}>
        选择一个预算类型开始规划您的财务未来
      </Text>
      <Row gutter={[24, 24]}>
        {budgetTypes.map((type) => (
          <Col xs={24} sm={12} md={8} key={type.key}>
            <Card
              hoverable
              onClick={() => navigate(`/budget-calculator?type=${type.key}`)}
              style={{
                borderRadius: 12,
                height: '100%',
                border: '1px solid #f0f0f0',
                cursor: 'pointer',
              }}
              styles={{
                body: {
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  justifyContent: 'center',
                  padding: '40px 24px',
                  textAlign: 'center',
                },
              }}
            >
              <Space direction="vertical" size="large" style={{ alignItems: 'center' }}>
                <div style={{
                  width: 64,
                  height: 64,
                  borderRadius: 16,
                  backgroundColor: type.color + '15',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  color: type.color,
                }}>
                  {type.icon}
                </div>
                <div>
                  <Text strong style={{ fontSize: 18, display: 'block', marginBottom: 8 }}>
                    {type.title}
                  </Text>
                  <Text type="secondary" style={{ fontSize: 14 }}>
                    {type.description}
                  </Text>
                </div>
                <Text style={{ color: type.color }}>
                  <Space><span>开始规划</span><ArrowRight size={16} /></Space>
                </Text>
              </Space>
            </Card>
          </Col>
        ))}
      </Row>
    </div>
  );
};

// src/pages/BudgetPlan.vue
<template>
  <div class="budget-plan-page">
    <h4 class="page-title">预算计划</h4>
    <p class="page-desc">选择一个预算类型开始规划您的财务未来</p>
    <el-row :gutter="24">
      <el-col v-for="type in budgetTypes" :key="type.key" :xs="24" :sm="12" :md="8">
        <el-card
          class="budget-type-card"
          shadow="hover"
          @click="navigateToCalculator(type.key)"
        >
          <div class="card-body">
            <div class="icon-wrapper" :style="{ backgroundColor: type.color + '15', color: type.color }">
              <el-icon :size="28"><component :is="type.icon" /></el-icon>
            </div>
            <div class="text-section">
              <strong class="title-text">{{ type.title }}</strong>
              <span class="desc-text">{{ type.description }}</span>
            </div>
            <div class="action-text" :style="{ color: type.color }">
              <el-space>
                <span>开始规划</span>
                <el-icon :size="16"><ArrowRight /></el-icon>
              </el-space>
            </div>
          </div>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router'
import { Top, Histogram, Coin, ArrowRight } from '@element-plus/icons-vue'

const router = useRouter()

const budgetTypes = [
  { key: 'balance', title: '账户余额预测', description: '预测账户未来余额变化趋势', icon: Top, color: '#1677ff' },
  { key: 'trend', title: '收入支出趋势', description: '分析未来收支趋势和变化', icon: Histogram, color: '#52c41a' },
  { key: 'savings', title: '储蓄目标规划', description: '规划储蓄目标和实现进度', icon: Coin, color: '#fa8c16' },
]

const navigateToCalculator = (key: string) => {
  router.push(`/budget-calculator?type=${key}`)
}
</script>

<style scoped>
.budget-plan-page {
  padding: 24px;
}
.page-title {
  margin: 0 0 16px 0;
  font-size: 16px;
  font-weight: 600;
}
.page-desc {
  color: #909399;
  margin: 0 0 32px 0;
  font-size: 16px;
}
.budget-type-card {
  border-radius: 12px;
  height: 100%;
  border: 1px solid #f0f0f0;
  cursor: pointer;
}
.card-body {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 40px 24px;
  text-align: center;
}
.icon-wrapper {
  width: 64px;
  height: 64px;
  border-radius: 16px;
  display: flex;
  align-items: center;
  justify-content: center;
}
.text-section {
  margin-top: 16px;
}
.title-text {
  font-size: 18px;
  display: block;
  margin-bottom: 8px;
}
.desc-text {
  color: #909399;
  font-size: 14px;
}
.action-text {
  margin-top: 16px;
}
</style>
