// src/pages/Dashboard.vue
<template>
  <div>
    <div class="dashboard-header">
      <h4 class="dashboard-title">{{ t.dashboard.title }}</h4>
      <el-button size="small" @click="toggleLanguage">
        <el-icon><Switch /></el-icon>
        {{ language === 'zh' ? 'EN' : '中文' }}
      </el-button>
    </div>

    <el-row :gutter="16" class="stats-row">
      <el-col :xs="24" :sm="8">
        <el-card shadow="hover" class="stat-card">
          <el-space :size="16">
            <div class="stat-icon income-icon">
              <el-icon :size="24" color="#22c55e"><TrendCharts /></el-icon>
            </div>
            <div>
              <span class="stat-label">{{ t.dashboard.totalIncome }}</span>
              <div class="stat-value income-color">{{ formatCurrency(statistics.totalIncome) }}</div>
            </div>
          </el-space>
        </el-card>
      </el-col>
      <el-col :xs="24" :sm="8">
        <el-card shadow="hover" class="stat-card">
          <el-space :size="16">
            <div class="stat-icon expense-icon">
              <el-icon :size="24" color="#ef4444"><TrendCharts /></el-icon>
            </div>
            <div>
              <span class="stat-label">{{ t.dashboard.totalExpense }}</span>
              <div class="stat-value expense-color">{{ formatCurrency(statistics.totalExpense) }}</div>
            </div>
          </el-space>
        </el-card>
      </el-col>
      <el-col :xs="24" :sm="8">
        <el-card shadow="hover" class="stat-card">
          <el-space :size="16">
            <div class="stat-icon balance-icon">
              <el-icon :size="24" color="#3b82f6"><Wallet /></el-icon>
            </div>
            <div>
              <span class="stat-label">{{ t.dashboard.balance }}</span>
              <div class="stat-value balance-color">{{ formatCurrency(statistics.balance) }}</div>
            </div>
          </el-space>
        </el-card>
      </el-col>
    </el-row>

    <div class="charts-section">
      <BalanceChart />
      <ExpenseChart />
      <IncomeChart />
    </div>

    <el-card class="recent-card" :body-style="{ padding: 0 }">
      <template #header>
        <span>{{ t.dashboard.recentTransactions }}</span>
      </template>
      <div v-if="recentRecords.length === 0" class="empty-wrapper">
        <el-empty>
          <template #description>
            <p>{{ t.dashboard.noRecords }}</p>
            <p class="hint-text">{{ t.dashboard.addFirstRecord }}</p>
          </template>
        </el-empty>
      </div>
      <div v-else>
        <div v-for="record in recentRecords" :key="record.id" class="record-item">
          <div class="record-main">
            <div class="record-meta">
              <el-tag :type="record.type === 'income' ? 'success' : 'danger'" size="small">
                {{ record.type === 'income' ? t.dashboard.income : t.dashboard.expense }}
              </el-tag>
              <span class="record-category">{{ record.category }}</span>
              <span class="record-note">{{ record.note || record.category }}</span>
            </div>
            <span class="record-date">{{ formatDate(record.date) }}</span>
          </div>
          <div class="record-actions">
            <span
              class="record-amount"
              :class="record.type === 'income' ? 'income-color' : 'expense-color'"
            >
              {{ record.type === 'income' ? '+' : '-' }}{{ formatCurrency(record.amount) }}
            </span>
            <el-popconfirm
              :title="t.common?.confirmDelete || '确定删除?'"
              @confirm="deleteRecord(record.id)"
            >
              <template #reference>
                <el-button type="danger" link size="small">
                  <el-icon><Delete /></el-icon>
                </el-button>
              </template>
            </el-popconfirm>
          </div>
        </div>
      </div>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { TrendCharts, Wallet, Delete, Switch } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import BalanceChart from '../components/BalanceChart.vue'
import ExpenseChart from '../components/ExpenseChart.vue'
import IncomeChart from '../components/IncomeChart.vue'
import { useLanguage } from '../composables/useLanguage'
import { useRecords } from '../composables/useRecords'
import { useStatistics } from '../composables/useStatistics'

const { t, language, toggleLanguage } = useLanguage()
const { getRecentRecords, deleteRecord } = useRecords()
const { statistics, formatCurrency, formatDate } = useStatistics()

const recentRecords = computed(() => getRecentRecords(10))
</script>

<style scoped>
.dashboard-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
}
.dashboard-title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
}
.stats-row {
  margin-bottom: 32px;
}
.stat-card :deep(.el-card__body) {
  padding: 20px;
}
.stat-icon {
  padding: 12px;
  border-radius: 8px;
}
.income-icon {
  background-color: rgba(34, 197, 94, 0.1);
}
.expense-icon {
  background-color: rgba(239, 68, 68, 0.1);
}
.balance-icon {
  background-color: rgba(59, 130, 246, 0.1);
}
.stat-label {
  font-size: 14px;
  color: #909399;
}
.stat-value {
  font-size: 24px;
  font-weight: bold;
}
.income-color {
  color: #22c55e;
}
.expense-color {
  color: #ef4444;
}
.balance-color {
  color: #3b82f6;
}
.charts-section {
  margin-bottom: 32px;
  display: flex;
  flex-direction: column;
  gap: 24px;
}
.recent-card {
  margin-bottom: 16px;
}
.empty-wrapper {
  padding: 48px 0;
}
.hint-text {
  font-size: 12px;
  color: #999;
  margin-top: 4px;
}
.record-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 24px;
  border-bottom: 1px solid #f0f0f0;
}
.record-item:last-child {
  border-bottom: none;
}
.record-main {
  flex: 1;
}
.record-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 4px;
}
.record-category {
  font-size: 14px;
  color: #909399;
}
.record-note {
  font-size: 14px;
  font-weight: 600;
}
.record-date {
  font-size: 12px;
  color: #909399;
}
.record-actions {
  display: flex;
  align-items: center;
  gap: 12px;
}
.record-amount {
  font-size: 16px;
  font-weight: 600;
}
</style>

// src/pages/Dashboard.tsx
import { TrendingUp, TrendingDown, Wallet, Trash2, Globe } from 'lucide-react';
import { Card, Row, Col, Button, Tag, List, Typography, Space, Empty } from 'antd';
import { BalanceChart } from '../components/BalanceChart';
import { ExpenseChart } from '../components/ExpenseChart';
import { IncomeChart } from '../components/IncomeChart';
import { useLanguage } from '../contexts/LanguageContext';
import { useRecords } from '../hooks/useRecords';
import { useStatistics } from '../hooks/useStatistics';

const { Text } = Typography;

export const Dashboard = () => {
  const { t, language, toggleLanguage } = useLanguage();
  const { getRecentRecords, deleteRecord } = useRecords();
  const { statistics, formatCurrency, formatDate } = useStatistics();

  const recentRecords = getRecentRecords(10);

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 }}>
        <h1 style={{ fontSize: 24, fontWeight: 'bold', margin: 0 }}>{t.dashboard.title}</h1>
        <Button
          onClick={toggleLanguage}
          icon={<Globe className="w-4 h-4" />}
        >
          {language === 'zh' ? 'EN' : '中文'}
        </Button>
      </div>

      <Row gutter={[16, 16]} style={{ marginBottom: 32 }}>
        <Col xs={24} sm={8}>
          <Card
            bordered={false}
            styles={{ body: { padding: '20px' } }}
          >
            <Space size={16}>
              <div style={{
                padding: 12,
                borderRadius: 8,
                backgroundColor: 'rgba(34, 197, 94, 0.1)',
              }}>
                <TrendingUp style={{ width: 24, height: 24, color: '#22c55e' }} />
              </div>
              <div>
                <Text type="secondary" style={{ fontSize: 14 }}>{t.dashboard.totalIncome}</Text>
                <div style={{ fontSize: 24, fontWeight: 'bold', color: '#22c55e' }}>
                  {formatCurrency(statistics.totalIncome)}
                </div>
              </div>
            </Space>
          </Card>
        </Col>
        <Col xs={24} sm={8}>
          <Card
            bordered={false}
            styles={{ body: { padding: '20px' } }}
          >
            <Space size={16}>
              <div style={{
                padding: 12,
                borderRadius: 8,
                backgroundColor: 'rgba(239, 68, 68, 0.1)',
              }}>
                <TrendingDown style={{ width: 24, height: 24, color: '#ef4444' }} />
              </div>
              <div>
                <Text type="secondary" style={{ fontSize: 14 }}>{t.dashboard.totalExpense}</Text>
                <div style={{ fontSize: 24, fontWeight: 'bold', color: '#ef4444' }}>
                  {formatCurrency(statistics.totalExpense)}
                </div>
              </div>
            </Space>
          </Card>
        </Col>
        <Col xs={24} sm={8}>
          <Card
            bordered={false}
            styles={{ body: { padding: '20px' } }}
          >
            <Space size={16}>
              <div style={{
                padding: 12,
                borderRadius: 8,
                backgroundColor: 'rgba(59, 130, 246, 0.1)',
              }}>
                <Wallet style={{ width: 24, height: 24, color: '#3b82f6' }} />
              </div>
              <div>
                <Text type="secondary" style={{ fontSize: 14 }}>{t.dashboard.balance}</Text>
                <div style={{ fontSize: 24, fontWeight: 'bold', color: '#3b82f6' }}>
                  {formatCurrency(statistics.balance)}
                </div>
              </div>
            </Space>
          </Card>
        </Col>
      </Row>

      <div style={{ marginBottom: 32, display: 'flex', flexDirection: 'column', gap: 24 }}>
        <BalanceChart />
        <ExpenseChart />
        <IncomeChart />
      </div>

      <Card
        title={t.dashboard.recentTransactions}
        bordered={false}
        styles={{ body: { padding: 0 } }}
      >
        {recentRecords.length === 0 ? (
          <Empty
            image={Empty.PRESENTED_IMAGE_SIMPLE}
            description={
              <div>
                <p>{t.dashboard.noRecords}</p>
                <p style={{ fontSize: 12, color: '#999', marginTop: 4 }}>{t.dashboard.addFirstRecord}</p>
              </div>
            }
            style={{ padding: '48px 0' }}
          />
        ) : (
          <List
            dataSource={recentRecords}
            renderItem={(record) => (
              <List.Item
                style={{ padding: '12px 24px' }}
                actions={[
                  <Button
                    type="text"
                    danger
                    size="small"
                    icon={<Trash2 className="w-4 h-4" />}
                    onClick={() => deleteRecord(record.id)}
                    title={t.dashboard.deleteRecord}
                  />,
                ]}
              >
                <List.Item.Meta
                  title={
                    <Space>
                      <Tag color={record.type === 'income' ? 'green' : 'red'}>
                        {record.type === 'income' ? t.dashboard.income : t.dashboard.expense}
                      </Tag>
                      <Text type="secondary">{record.category}</Text>
                      <Text strong>{record.note || record.category}</Text>
                    </Space>
                  }
                  description={formatDate(record.date)}
                />
                <Text
                  strong
                  style={{
                    color: record.type === 'income' ? '#22c55e' : '#ef4444',
                    fontSize: 16,
                  }}
                >
                  {record.type === 'income' ? '+' : '-'}
                  {formatCurrency(record.amount)}
                </Text>
              </List.Item>
            )}
          />
        )}
      </Card>
    </div>
  );
};
