// src/pages/History.vue
<template>
  <div>
    <h4 class="page-title">
      <el-icon class="title-icon" color="#1677ff"><Clock /></el-icon>
      {{ t.history.title }}
    </h4>

    <div v-if="sortedMonths.length === 0" class="empty-wrapper">
      <el-card>
        <el-empty>
          <template #description>
            <p>{{ t.history.noRecords }}</p>
            <p class="hint-text">{{ t.history.addFirstRecord }}</p>
          </template>
        </el-empty>
      </el-card>
    </div>

    <div v-else class="months-container">
      <el-card v-for="month in sortedMonths" :key="month" class="month-card">
        <template #header>
          <div class="month-header">
            <span>{{ formatMonth(month) }}</span>
            <div class="month-summary">
              <span class="summary-item income-summary">
                <el-icon color="#22c55e"><Top /></el-icon>
                {{ t.history.income }}:
                <span class="income-color">+{{ formatCurrency(groupedRecords[month].totalIncome) }}</span>
              </span>
              <span class="summary-item expense-summary">
                <el-icon color="#ef4444"><Bottom /></el-icon>
                {{ t.history.expense }}:
                <span class="expense-color">-{{ formatCurrency(groupedRecords[month].totalExpense) }}</span>
              </span>
            </div>
          </div>
        </template>
        <el-table :data="groupedRecords[month].records" row-key="id" size="default" :pagination="false">
          <el-table-column :label="t.history.time" prop="date" width="140">
            <template #default="{ row }">
              {{ formatDate(row.date) }}
            </template>
          </el-table-column>
          <el-table-column :label="t.history.category" prop="category" min-width="120" />
          <el-table-column :label="t.history.amount" width="140">
            <template #default="{ row }">
              <span
                class="amount-text"
                :class="row.type === 'income' ? 'income-color' : 'expense-color'"
              >
                {{ row.type === 'income' ? '+' : '-' }}{{ formatCurrency(row.amount) }}
              </span>
            </template>
          </el-table-column>
          <el-table-column :label="t.history.type" width="100">
            <template #default="{ row }">
              <el-tag :type="row.type === 'income' ? 'success' : 'danger'" size="small">
                {{ row.type === 'income' ? t.history.incomeType : t.history.expenseType }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column :label="t.history.description" prop="note" min-width="120">
            <template #default="{ row }">
              {{ row.note || '-' }}
            </template>
          </el-table-column>
        </el-table>
      </el-card>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Clock, Top, Bottom } from '@element-plus/icons-vue'
import { useLanguage } from '../composables/useLanguage'
import { useRecords } from '../composables/useRecords'
import { useStatistics } from '../composables/useStatistics'
import type { ExpenseRecord } from '../types/record'

const { t, language } = useLanguage()
const { records } = useRecords()
const { formatCurrency, formatDate } = useStatistics()

interface GroupedData {
  records: ExpenseRecord[]
  totalIncome: number
  totalExpense: number
}

const groupedRecords = computed<Record<string, GroupedData>>(() => {
  const grouped: Record<string, GroupedData> = {}
  const sortedRecords = [...records.value].sort((a, b) => b.date.localeCompare(a.date))
  sortedRecords.forEach((record) => {
    const monthKey = record.date.substring(0, 7)
    if (!grouped[monthKey]) {
      grouped[monthKey] = { records: [], totalIncome: 0, totalExpense: 0 }
    }
    grouped[monthKey].records.push(record)
    if (record.type === 'income') {
      grouped[monthKey].totalIncome += record.amount
    } else {
      grouped[monthKey].totalExpense += record.amount
    }
  })
  return grouped
})

const formatMonth = (monthKey: string) => {
  const [year, month] = monthKey.split('-')
  return language.value === 'zh' ? `${year}年${parseInt(month)}月` : `${year}-${month}`
}

const sortedMonths = computed(() =>
  Object.keys(groupedRecords.value).sort((a, b) => b.localeCompare(a))
)
</script>

<style scoped>
.page-title {
  display: flex;
  align-items: center;
  margin-bottom: 16px;
  font-size: 16px;
  font-weight: 600;
}
.title-icon {
  margin-right: 8px;
}
.empty-wrapper {
  margin-top: 16px;
}
.hint-text {
  font-size: 12px;
  color: #999;
  margin-top: 4px;
}
.months-container {
  display: flex;
  flex-direction: column;
  gap: 24px;
}
.month-card {
  margin-bottom: 0;
}
.month-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.month-summary {
  display: flex;
  gap: 24px;
}
.summary-item {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 14px;
}
.income-color {
  color: #22c55e;
  font-weight: 600;
}
.expense-color {
  color: #ef4444;
  font-weight: 600;
}
.amount-text {
  font-weight: 600;
}
</style>

// src/pages/History.tsx
import { useMemo } from 'react';
import { Card, Table, Tag, Typography, Empty } from 'antd';
import { History as HistoryIcon, TrendingUp, TrendingDown } from 'lucide-react';
import { useLanguage } from '../contexts/LanguageContext';
import { useRecords } from '../hooks/useRecords';
import { useStatistics } from '../hooks/useStatistics';
import type { ExpenseRecord } from '../types/record';
import type { ColumnsType } from 'antd/es/table';

const { Title, Text } = Typography;

interface GroupedRecords {
  [key: string]: {
    records: ExpenseRecord[];
    totalIncome: number;
    totalExpense: number;
  };
}

export const History = () => {
  const { t } = useLanguage();
  const { records } = useRecords();
  const { formatCurrency, formatDate } = useStatistics();

  // 按月份分组并计算统计
  const groupedRecords = useMemo(() => {
    const grouped: GroupedRecords = {};

    const sortedRecords = [...records].sort((a, b) => b.date.localeCompare(a.date));

    sortedRecords.forEach((record) => {
      const monthKey = record.date.substring(0, 7);

      if (!grouped[monthKey]) {
        grouped[monthKey] = {
          records: [],
          totalIncome: 0,
          totalExpense: 0,
        };
      }

      grouped[monthKey].records.push(record);

      if (record.type === 'income') {
        grouped[monthKey].totalIncome += record.amount;
      } else {
        grouped[monthKey].totalExpense += record.amount;
      }
    });

    return grouped;
  }, [records]);

  const formatMonth = (monthKey: string) => {
    const [year, month] = monthKey.split('-');
    return `${year}年${parseInt(month)}月`;
  };

  const sortedMonths = useMemo(() => {
    return Object.keys(groupedRecords).sort((a, b) => b.localeCompare(a));
  }, [groupedRecords]);

  const columns: ColumnsType<ExpenseRecord> = useMemo(() => [
    {
      title: t.history.time,
      dataIndex: 'date',
      key: 'date',
      render: (date: string) => formatDate(date),
    },
    {
      title: t.history.category,
      dataIndex: 'category',
      key: 'category',
    },
    {
      title: t.history.amount,
      dataIndex: 'amount',
      key: 'amount',
      render: (amount: number, record: ExpenseRecord) => (
        <Text strong style={{ color: record.type === 'income' ? '#22c55e' : '#ef4444' }}>
          {record.type === 'income' ? '+' : '-'}{formatCurrency(amount)}
        </Text>
      ),
    },
    {
      title: t.history.type,
      dataIndex: 'type',
      key: 'type',
      render: (type: string) => (
        <Tag color={type === 'income' ? 'green' : 'red'}>
          {type === 'income' ? t.history.incomeType : t.history.expenseType}
        </Tag>
      ),
    },
    {
      title: t.history.description,
      dataIndex: 'note',
      key: 'note',
      render: (note: string) => note || '-',
    },
  ], [formatCurrency, formatDate, t]);

  if (sortedMonths.length === 0) {
    return (
      <div>
        <Title level={4} style={{ marginBottom: 16 }}>
          <HistoryIcon className="w-8 h-8 inline-block mr-2" style={{ verticalAlign: 'middle' }} />
          {t.history.title}
        </Title>
        <Card bordered={false}>
          <Empty
            image={Empty.PRESENTED_IMAGE_SIMPLE}
            description={
              <div>
                <p>{t.history.noRecords}</p>
                <p style={{ fontSize: 12, color: '#999', marginTop: 4 }}>{t.history.addFirstRecord}</p>
              </div>
            }
            style={{ padding: '48px 0' }}
          />
        </Card>
      </div>
    );
  }

  return (
    <div>
      <Title level={4} style={{ marginBottom: 16 }}>
        <HistoryIcon className="w-8 h-8 inline-block mr-2" style={{ verticalAlign: 'middle', color: '#1677ff' }} />
        {t.history.title}
      </Title>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
        {sortedMonths.map((month) => {
          const monthData = groupedRecords[month];

          return (
            <Card
              key={month}
              bordered={false}
              title={
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <span>{formatMonth(month)}</span>
                  <div style={{ display: 'flex', gap: 24 }}>
                    <span>
                      <TrendingUp className="w-4 h-4 inline-block mr-1" style={{ color: '#22c55e', verticalAlign: 'middle' }} />
                      <Text type="secondary" style={{ marginRight: 4 }}>{t.history.income}:</Text>
                      <Text strong style={{ color: '#22c55e' }}>+{formatCurrency(monthData.totalIncome)}</Text>
                    </span>
                    <span>
                      <TrendingDown className="w-4 h-4 inline-block mr-1" style={{ color: '#ef4444', verticalAlign: 'middle' }} />
                      <Text type="secondary" style={{ marginRight: 4 }}>{t.history.expense}:</Text>
                      <Text strong style={{ color: '#ef4444' }}>-{formatCurrency(monthData.totalExpense)}</Text>
                    </span>
                  </div>
                </div>
              }
            >
              <Table
                columns={columns}
                dataSource={monthData.records}
                rowKey="id"
                pagination={false}
                size="middle"
              />
            </Card>
          );
        })}
      </div>
    </div>
  );
};
