// src/components/Sidebar.vue
<template>
  <el-aside
    width="240px"
    class="sidebar"
  >
    <div class="sidebar-header">
      <div class="sidebar-title">{{ t.sidebar.title }}</div>
      <el-button
        type="info"
        link
        size="small"
        @click="onCollapse"
        :title="t.sidebar.collapse || '折叠侧边栏'"
      >
        <el-icon :size="16"><Close /></el-icon>
      </el-button>
    </div>
    <el-menu
      :default-active="currentPage"
      class="sidebar-menu"
      @select="handleSelect"
    >
      <el-menu-item index="dashboard">
        <el-icon><Odometer /></el-icon>
        <span>{{ t.sidebar.dashboard }}</span>
      </el-menu-item>
      <el-menu-item index="history">
        <el-icon><Clock /></el-icon>
        <span>{{ t.sidebar.history }}</span>
      </el-menu-item>
      <el-menu-item index="accounts">
        <el-icon><Wallet /></el-icon>
        <span>{{ t.sidebar.accounts }}</span>
      </el-menu-item>
      <el-menu-item v-if="hasMultiCurrency" index="exchange-rate">
        <el-icon><Money /></el-icon>
        <span>{{ t.sidebar.exchangeRate }}</span>
      </el-menu-item>
      <el-menu-item index="financial-config">
        <el-icon><Setting /></el-icon>
        <span>{{ t.sidebar.financialConfig }}</span>
      </el-menu-item>
      <el-menu-item index="budget-plan">
        <el-icon><Aim /></el-icon>
        <span>{{ t.sidebar.budgetPlan }}</span>
      </el-menu-item>
      <el-menu-item index="budget-calculator">
        <el-icon><Tools /></el-icon>
        <span>{{ t.sidebar.budgetCalculator }}</span>
      </el-menu-item>
      <el-menu-item index="add-record">
        <el-icon><CirclePlus /></el-icon>
        <span>{{ t.sidebar.addRecord }}</span>
      </el-menu-item>
      <el-menu-item index="settings">
        <el-icon><Setting /></el-icon>
        <span>{{ t.sidebar.settings }}</span>
      </el-menu-item>
    </el-menu>
  </el-aside>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import {
  Odometer,
  Clock,
  Wallet,
  Money,
  Setting,
  Aim,
  CirclePlus,
  Close,
  Tools,
} from '@element-plus/icons-vue'
import { useLanguage } from '../composables/useLanguage'
import { useRecords } from '../composables/useRecords'

interface SidebarProps {
  onCollapse: () => void
}

const props = defineProps<SidebarProps>()

const router = useRouter()
const route = useRoute()
const { t } = useLanguage()
const { accounts } = useRecords()

const defaultCurrency = computed(() =>
  accounts.value.find(a => a.isDefault)?.currency || 'CNY'
)

const hasMultiCurrency = computed(() =>
  accounts.value.some(a => a.currency !== defaultCurrency.value && a.visible)
)

const currentPage = computed(() => {
  const path = route.path
  if (path === '/calc' || path === '/calc/') return 'dashboard'
  return path.replace('/calc/', '') || 'dashboard'
})

function handleSelect(key: string) {
  if (key === 'dashboard') {
    router.push('/calc/')
  } else {
    router.push(`/calc/${key}`)
  }
}
</script>

<style scoped>
.sidebar {
  border-right: 1px solid var(--el-border-color-light, #d9d9d9);
  height: 100vh;
  position: sticky;
  top: 0;
  overflow: auto;
  background: var(--el-bg-color, #fff);
}

.sidebar-header {
  padding: 16px;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.sidebar-title {
  font-size: 18px;
  font-weight: bold;
  color: var(--el-text-color-primary, #000);
}

.sidebar-menu {
  border-right: none;
}
</style>

// src/components/Sidebar.tsx
import {
  LayoutDashboard,
  PlusCircle,
  Settings,
  History,
  X,
  Wallet,
  Settings2,
  Target,
  Banknote,
} from 'lucide-react';
import { Layout, Menu, Button } from 'antd';
import { useLocation, useNavigate } from 'react-router-dom';
import { useLanguage } from '../contexts/LanguageContext';
import { useRecords } from '../hooks/useRecords';

const { Sider } = Layout;

interface SidebarProps {
  onCollapse: () => void;
}

export const Sidebar = ({ onCollapse }: SidebarProps) => {
  const location = useLocation();
  const navigate = useNavigate();
  const { t } = useLanguage();
  const { accounts } = useRecords();

  const defaultCurrency = accounts.find(a => a.isDefault)?.currency || 'CNY';
  const hasMultiCurrency = accounts.some(a => a.currency !== defaultCurrency && a.visible);

  const currentPage = location.pathname.slice(1) || 'dashboard';

  const menuItems = [
    { key: 'dashboard', label: t.sidebar.dashboard, icon: <LayoutDashboard className="w-[16px] h-[16px]" /> },
    { key: 'history', label: t.sidebar.history, icon: <History className="w-[16px] h-[16px]" /> },
    { key: 'accounts', label: t.sidebar.accounts, icon: <Wallet className="w-[16px] h-[16px]" /> },
    ...(hasMultiCurrency ? [{ key: 'exchange-rate' as const, label: t.sidebar.exchangeRate, icon: <Banknote className="w-[16px] h-[16px]" /> }] : []),
    { key: 'financial-config', label: t.sidebar.financialConfig, icon: <Settings2 className="w-[16px] h-[16px]" /> },
    { key: 'budget-plan', label: t.sidebar.budgetPlan, icon: <Target className="w-[16px] h-[16px]" /> },
    { key: 'add-record', label: t.sidebar.addRecord, icon: <PlusCircle className="w-[16px] h-[16px]" /> },
    { key: 'settings', label: t.sidebar.settings, icon: <Settings className="w-[16px] h-[16px]" /> },
  ];

  return (
    <Sider
      width={240}
      trigger={null}
      collapsible={false}
      theme="light"
      style={{
        borderRight: '1px solid var(--ant-color-border, #d9d9d9)',
        height: '100vh',
        position: 'sticky',
        top: 0,
        overflow: 'auto',
      }}
    >
      <div style={{ padding: '16px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ fontSize: '18px', fontWeight: 'bold', color: 'var(--ant-color-text, #000)' }}>
          {t.sidebar.title}
        </div>
        <Button
          type="text"
          size="small"
          icon={<X className="w-4 h-4" />}
          onClick={onCollapse}
          title={t.sidebar.collapse || '折叠侧边栏'}
        />
      </div>
      <Menu
        mode="inline"
        selectedKeys={[currentPage]}
        items={menuItems as any}
        onClick={({ key }) => navigate(key === 'dashboard' ? '/' : `/${key}`)}
        style={{ borderRight: 'none' }}
      />
    </Sider>
  );
};
