// src/pages/ExchangeRate.vue
<template>
  <div>
    <div class="exchange-header">
      <el-space>
        <el-button text @click="router.push('/settings')">
          <el-icon><ArrowLeft /></el-icon>
        </el-button>
        <h4 class="exchange-title">{{ t.exchangeRate.title }}</h4>
      </el-space>
    </div>

    <template v-if="!hasMultiCurrency">
      <el-alert :title="t.exchangeRate.noMultiCurrency" type="info" :closable="false" show-icon style="margin-bottom: 16px" />
    </template>
    <template v-else>
      <el-space direction="vertical" :size="16" class="full-width">
        <el-card>
          <template #header>
            <div class="card-header-between">
              <span>{{ t.exchangeRate.title }}</span>
              <el-space>
                <template v-if="!isEditing">
                  <el-button @click="handleFetchFromAPI" :loading="isFetching" :disabled="isFetching">
                    <el-icon><Refresh /></el-icon>
                    {{ t.exchangeRate.fetchFromAPI }}
                  </el-button>
                  <el-button type="primary" @click="handleStartEdit">
                    <el-icon><Edit /></el-icon>
                    {{ t.exchangeRate.manualEdit }}
                  </el-button>
                </template>
                <template v-else>
                  <el-button @click="handleCancelEdit">{{ t.exchangeRate.cancel }}</el-button>
                  <el-button type="primary" @click="handleSave">
                    <el-icon><Check /></el-icon>
                    {{ t.exchangeRate.save }}
                  </el-button>
                </template>
              </el-space>
            </div>
          </template>
          <el-space direction="vertical" :size="8">
            <div>
              <span class="secondary-text">{{ t.exchangeRate.baseCurrency }}: </span>
              <strong>{{ defaultCurrency }}</strong>
            </div>
            <div>
              <span class="secondary-text">{{ t.exchangeRate.lastUpdate }}: </span>
              <span>{{ formatLastUpdate(exchangeRates.lastUpdatedAt) }}</span>
            </div>
            <div>
              <span class="secondary-text">{{ t.exchangeRate.source }}: </span>
              <el-tag :color="sourceTagColor(exchangeRates.source)">{{ getSourceText(exchangeRates.source) }}</el-tag>
              <span v-if="exchangeRates.source === 'api' && exchangeRates.apiSource" class="secondary-text" style="margin-left: 8px">
                {{ exchangeRates.apiSource }}
              </span>
            </div>
            <div v-if="isEditing">
              <span class="secondary-text">{{ t.exchangeRate.availableApis }}: </span>
              <el-space wrap>
                <el-tag v-for="api in EXCHANGE_RATE_APIS" :key="api.name" type="info">{{ api.name }}</el-tag>
              </el-space>
            </div>
          </el-space>
        </el-card>

        <el-card>
          <el-table :data="tableData" stripe size="small">
            <el-table-column prop="currency" :label="t.exchangeRate.currency" width="120">
              <template #default="{ row }">
                <strong>{{ row.currency }}</strong>
              </template>
            </el-table-column>
            <el-table-column :label="t.exchangeRate.rate" width="200">
              <template #default="{ row }">
                <template v-if="isEditing">
                  <el-input-number
                    :model-value="parseFloat(editingRates[row.currency as string] ?? '')"
                    @update:model-value="val => editingRates[row.currency as string] = String(val ?? '')"
                    :placeholder="`1 ${defaultCurrency} = ? ${row.currency}`"
                    :step="0.0001"
                    :precision="4"
                    :min="0"
                    controls-position="right"
                    style="width: 100%"
                  />
                </template>
                <template v-else>
                  <span>1 {{ defaultCurrency }} = {{ row.rate }} {{ row.currency }}</span>
                </template>
              </template>
            </el-table-column>
          </el-table>
        </el-card>
      </el-space>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowLeft, Refresh, Edit, Check } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { useLanguage } from '../composables/useLanguage'
import { useRecords } from '../composables/useRecords'
import { DEFAULT_EXCHANGE_RATES, EXCHANGE_RATE_APIS } from '../types/record'

const router = useRouter()
const { t } = useLanguage()
const { exchangeRates, customCurrencies, updateExchangeRate, fetchExchangeRatesFromAPI, canFetchRatesFromAPI, accounts } = useRecords()

const isEditing = ref(false)
const editingRates = ref<Record<string, string>>({})
const isFetching = ref(false)

const defaultCurrency = computed(() => {
  const defaultAccount = accounts.value.find(a => a.isDefault)
  return defaultAccount?.currency || 'CNY'
})

const enabledCurrencies = computed(() => {
  const currencies = new Set<string>()
  accounts.value.forEach(a => {
    if (a.currency !== defaultCurrency.value && a.visible) {
      currencies.add(a.currency)
    }
  })
  customCurrencies.value.forEach(c => currencies.add(c.code))
  return Array.from(currencies).sort()
})

const tableData = computed(() => {
  return enabledCurrencies.value.map(currency => ({
    key: currency,
    currency,
    rate: exchangeRates.value.rates[currency] ?? DEFAULT_EXCHANGE_RATES[currency] ?? 0,
    editRate: editingRates.value[currency] ?? '',
  }))
})

const getSourceText = (source: string) => {
  switch (source) {
    case 'manual':
      return t.value.exchangeRate.sourceManual
    case 'api':
      return t.value.exchangeRate.sourceApi
    default:
      return t.value.exchangeRate.sourceDefault
  }
}

const sourceTagColor = (source: string) => {
  switch (source) {
    case 'api': return 'success'
    case 'manual': return ''
    default: return 'info'
  }
}

const formatLastUpdate = (timestamp: number) => {
  if (!timestamp) return '-'
  return new Date(timestamp).toLocaleString('zh-CN')
}

const hasMultiCurrency = computed(() => enabledCurrencies.value.length > 0)

const handleStartEdit = () => {
  const initial: Record<string, string> = {}
  enabledCurrencies.value.forEach(currency => {
    initial[currency] = String(exchangeRates.value.rates[currency] ?? DEFAULT_EXCHANGE_RATES[currency] ?? '')
  })
  editingRates.value = initial
  isEditing.value = true
}

const handleSave = () => {
  const rates: Record<string, number> = {}
  for (const [currency, value] of Object.entries(editingRates.value)) {
    const num = parseFloat(value)
    if (isNaN(num) || num <= 0) {
      ElMessage.error(t.value.exchangeRate.invalidRate)
      return
    }
    rates[currency] = num
  }
  updateExchangeRate(rates, defaultCurrency.value)
  ElMessage.success(t.value.exchangeRate.saveSuccess)
  isEditing.value = false
  editingRates.value = {}
}

const handleCancelEdit = () => {
  isEditing.value = false
  editingRates.value = {}
}

const handleFetchFromAPI = async () => {
  const canFetch = canFetchRatesFromAPI()
  if (!canFetch.allowed) {
    const hours = Math.ceil(canFetch.remainingHours)
    ElMessage.warning(t.value.exchangeRate.hoursLeft.replace('{hours}', String(hours)))
    return
  }

  isFetching.value = true
  try {
    const result = await fetchExchangeRatesFromAPI(defaultCurrency.value)
    if (result.success) {
      ElMessage.success(result.message || t.value.exchangeRate.fetchSuccess)
    } else {
      ElMessage.error(result.message || t.value.exchangeRate.fetchError)
    }
  } catch {
    ElMessage.error(t.value.exchangeRate.fetchError)
  } finally {
    isFetching.value = false
  }
}
</script>

<style scoped>
.exchange-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
}
.exchange-title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
}
.full-width {
  width: 100%;
}
.card-header-between {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.secondary-text {
  color: #909399;
}
</style>

// src/app/features/exchange-rate/index.tsx
import { useState, useMemo } from 'react';
import { Card, Button, Input, Space, Typography, Table, message, Alert, Tag } from 'antd';
import { RefreshCw, Save, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useCurrencies } from '../../hooks/use-currencies';
import { useRecords } from '../../hooks/use-records';
import { ROUTES } from '../../router/routes';
import { DEFAULT_EXCHANGE_RATES, type Account } from '../../../types/record';
import { recordService } from '../../../data/service';

const { Title, Text } = Typography;

interface ExchangeRateRow {
  key: string;
  currency: string;
  rate: number;
}

export function ExchangeRatePage() {
  const navigate = useNavigate();
  const { exchangeRates, customCurrencies, updateExchangeRate, fetchExchangeRatesFromAPI, canFetchRatesFromAPI } = useCurrencies();
  useRecords();
  const accounts: Account[] = useMemo(() => recordService.getAccounts(), []);

  const [isEditing, setIsEditing] = useState(false);
  const [editingRates, setEditingRates] = useState<Record<string, string>>({});
  const [isFetching, setIsFetching] = useState(false);

  const defaultCurrency = useMemo(() => {
    const defaultAccount = accounts.find(a => a.isDefault);
    return defaultAccount?.currency || 'CNY';
  }, [accounts]);

  const enabledCurrencies = useMemo(() => {
    const currencies = new Set<string>();
    accounts.forEach(a => {
      if (a.currency !== defaultCurrency && a.visible) currencies.add(a.currency);
    });
    customCurrencies.forEach(c => currencies.add(c.code));
    return Array.from(currencies).sort();
  }, [accounts, defaultCurrency, customCurrencies]);

  const tableData: ExchangeRateRow[] = useMemo(() =>
    enabledCurrencies.map(currency => ({
      key: currency,
      currency,
      rate: exchangeRates.rates[currency] ?? DEFAULT_EXCHANGE_RATES[currency] ?? 0,
    })),
    [enabledCurrencies, exchangeRates],
  );

  const handleStartEdit = () => {
    const initial: Record<string, string> = {};
    enabledCurrencies.forEach(currency => {
      initial[currency] = String(exchangeRates.rates[currency] ?? DEFAULT_EXCHANGE_RATES[currency] ?? '');
    });
    setEditingRates(initial);
    setIsEditing(true);
  };

  const handleSave = () => {
    const rates: Record<string, number> = {};
    for (const [currency, value] of Object.entries(editingRates)) {
      const num = parseFloat(value);
      if (isNaN(num) || num <= 0) { message.error('汇率无效'); return; }
      rates[currency] = num;
    }
    updateExchangeRate(rates, defaultCurrency);
    message.success('保存成功');
    setIsEditing(false);
    setEditingRates({});
  };

  const handleFetchFromAPI = async () => {
    const canFetch = canFetchRatesFromAPI();
    if (!canFetch.allowed) {
      message.warning(`请等待 ${Math.ceil(canFetch.remainingHours)} 小时后再次获取`);
      return;
    }
    setIsFetching(true);
    try {
      const result = await fetchExchangeRatesFromAPI(defaultCurrency);
      message.success(result.success ? result.message : result.message);
    } finally {
      setIsFetching(false);
    }
  };

  const formatLastUpdate = (timestamp: number) => {
    if (!timestamp) return '-';
    return new Date(timestamp).toLocaleString('zh-CN');
  };

  const getSourceText = (source: string) => {
    switch (source) {
      case 'manual': return '手动';
      case 'api': return 'API';
      default: return '默认';
    }
  };

  const columns = useMemo(() => {
    const cols = [
      {
        title: '币种',
        dataIndex: 'currency',
        key: 'currency',
        width: 120,
        render: (currency: string) => <Text strong>{currency}</Text>,
      },
      {
        title: '汇率',
        dataIndex: 'rate',
        key: 'rate',
        width: 200,
        render: (_: number, record: ExchangeRateRow) => {
          if (isEditing) {
            return (
              <Input
                type="number"
                value={editingRates[record.currency] ?? ''}
                onChange={(e) => setEditingRates(prev => ({ ...prev, [record.currency]: e.target.value }))}
                placeholder={`1 ${defaultCurrency} = ? ${record.currency}`}
                step="0.0001"
              />
            );
          }
          return <Text>{`1 ${defaultCurrency} = ${record.rate} ${record.currency}`}</Text>;
        },
      },
    ];
    return cols;
  }, [isEditing, editingRates, defaultCurrency]);

  const hasMultiCurrency = enabledCurrencies.length > 0;

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
        <Space>
          <Button type="text" icon={<ArrowLeft size={16} />} onClick={() => navigate(ROUTES.SETTINGS)}>
            返回
          </Button>
          <Title level={4} style={{ margin: 0 }}>汇率管理</Title>
        </Space>
      </div>

      {!hasMultiCurrency ? (
        <Alert message="未启用多币种功能" type="info" showIcon style={{ marginBottom: 16 }} />
      ) : (
        <Space direction="vertical" size={16} style={{ width: '100%' }}>
          <Card
            title="汇率信息"
            extra={
              <Space>
                {!isEditing ? (
                  <>
                    <Button icon={<RefreshCw size={14} />} onClick={handleFetchFromAPI} loading={isFetching}>
                      从 API 获取
                    </Button>
                    <Button type="primary" icon={<Save size={14} />} onClick={handleStartEdit}>
                      手动编辑
                    </Button>
                  </>
                ) : (
                  <>
                    <Button onClick={() => { setIsEditing(false); setEditingRates({}); }}>取消</Button>
                    <Button type="primary" icon={<Save size={14} />} onClick={handleSave}>保存</Button>
                  </>
                )}
              </Space>
            }
          >
            <Space direction="vertical" size={8}>
              <div><Text type="secondary">基准币种: </Text><Text strong>{defaultCurrency}</Text></div>
              <div><Text type="secondary">最后更新: </Text><Text>{formatLastUpdate(exchangeRates.lastUpdatedAt)}</Text></div>
              <div>
                <Text type="secondary">汇率来源: </Text>
                <Tag color={exchangeRates.source === 'api' ? 'green' : exchangeRates.source === 'manual' ? 'blue' : 'default'}>
                  {getSourceText(exchangeRates.source)}
                </Tag>
              </div>
            </Space>
          </Card>

          <Card bordered={false}>
            <Table dataSource={tableData} columns={columns} pagination={false} size="small" />
          </Card>
        </Space>
      )}
    </div>
  );
}
